# Generated by Django 5.2 on 2026-03-12 20:16

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import shared.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.SmallIntegerField(choices=[(5, 'AEROBICS'), (6, 'BADMINTON'), (7, 'BASEBALL'), (8, 'BASKETBALL'), (9, 'BIKING'), (10, 'BOXING'), (11, 'CLIMBING'), (12, 'CRICKET'), (13, 'CROSSFIT'), (14, 'DANCING'), (15, 'FOOTBALL'), (16, 'GOLF'), (4, 'GYM'), (17, 'HANDBALL'), (0, 'HIKING'), (18, 'KAYAKING'), (19, 'MARTIAL_ARTS'), (20, 'PILATES'), (21, 'RUGBY'), (1, 'RUNNING'), (22, 'SAILING'), (23, 'SKATEBOARDING'), (24, 'SKIING'), (25, 'SNOWBOARDING'), (2, 'SOCCER'), (26, 'SURFING'), (27, 'SWIMMING'), (3, 'TENNIS'), (28, 'VOLLEYBALL'), (29, 'WALKING'), (30, 'YOGA')], primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'main_app_activity',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'main_app_chat',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('address_line_1', models.CharField(max_length=64, null=True)),
                ('address_line_2', models.CharField(max_length=64, null=True)),
                ('zip_code', models.IntegerField(null=True)),
                ('country_code', models.CharField(choices=[(1, 'AF'), (2, 'AL'), (3, 'DZ'), (4, 'AS'), (5, 'AD'), (6, 'AO'), (7, 'AI'), (8, 'AQ'), (9, 'AG'), (10, 'AR'), (11, 'AM'), (12, 'AW'), (13, 'AU'), (14, 'AT'), (15, 'AZ'), (16, 'BS'), (17, 'BH'), (18, 'BD'), (19, 'BB'), (20, 'BY'), (21, 'BE'), (22, 'BZ'), (23, 'BJ'), (24, 'BM'), (25, 'BT'), (26, 'BO'), (27, 'BA'), (28, 'BW'), (29, 'BR'), (30, 'IO'), (31, 'BN'), (32, 'BG'), (33, 'BF'), (34, 'BI'), (35, 'KH'), (36, 'CM'), (37, 'CA'), (38, 'CV'), (39, 'KY'), (40, 'CF'), (41, 'TD'), (42, 'CL'), (43, 'CN'), (44, 'CO'), (45, 'KM'), (46, 'CG'), (47, 'CD'), (48, 'CK'), (49, 'CR'), (50, 'CI'), (51, 'HR'), (52, 'CU'), (53, 'CY'), (54, 'CZ'), (55, 'DK'), (56, 'DJ'), (57, 'DM'), (58, 'DO'), (59, 'EC'), (60, 'EG'), (61, 'SV'), (62, 'GQ'), (63, 'ER'), (64, 'EE'), (65, 'SZ'), (66, 'ET'), (67, 'FJ'), (68, 'FI'), (69, 'FR'), (70, 'GA'), (71, 'GM'), (72, 'GE'), (73, 'DE'), (74, 'GH'), (75, 'GR'), (76, 'GD'), (77, 'GT'), (78, 'GN'), (79, 'GW'), (80, 'GY'), (81, 'HT'), (82, 'HN'), (83, 'HU'), (84, 'IS'), (85, 'IN'), (86, 'ID'), (87, 'IR'), (88, 'IQ'), (89, 'IE'), (90, 'IL'), (91, 'IT'), (92, 'JM'), (93, 'JP'), (94, 'JO'), (95, 'KZ'), (96, 'KE'), (97, 'KI'), (98, 'KP'), (99, 'KR'), (100, 'KW'), (101, 'KG'), (102, 'LA'), (103, 'LV'), (104, 'LB'), (105, 'LS'), (106, 'LR'), (107, 'LY'), (108, 'LI'), (109, 'LT'), (110, 'LU'), (111, 'MG'), (112, 'MW'), (113, 'MY'), (114, 'MV'), (115, 'ML'), (116, 'MT'), (117, 'MH'), (118, 'MR'), (119, 'MU'), (120, 'MX'), (121, 'FM'), (122, 'MD'), (123, 'MC'), (124, 'MN'), (125, 'ME'), (126, 'MA'), (127, 'MZ'), (128, 'MM'), (129, 'NA'), (130, 'NR'), (131, 'NP'), (132, 'NL'), (133, 'NZ'), (134, 'NI'), (135, 'NE'), (136, 'NG'), (137, 'MK'), (138, 'NO'), (139, 'OM'), (140, 'PK'), (141, 'PW'), (142, 'PS'), (143, 'PA'), (144, 'PG'), (145, 'PY'), (146, 'PE'), (147, 'PH'), (148, 'PL'), (149, 'PT'), (150, 'QA'), (151, 'RO'), (152, 'RU'), (153, 'RW'), (154, 'KN'), (155, 'LC'), (156, 'VC'), (157, 'WS'), (158, 'SM'), (159, 'ST'), (160, 'SA'), (161, 'SN'), (162, 'RS'), (163, 'SC'), (164, 'SL'), (165, 'SG'), (166, 'SK'), (167, 'SI'), (168, 'SB'), (169, 'SO'), (170, 'ZA'), (171, 'SS'), (172, 'ES'), (173, 'LK'), (174, 'SD'), (175, 'SR'), (176, 'SE'), (177, 'CH'), (178, 'SY'), (179, 'TW'), (180, 'TJ'), (181, 'TZ'), (182, 'TH'), (183, 'TL'), (184, 'TG'), (185, 'TO'), (186, 'TT'), (187, 'TN'), (188, 'TR'), (189, 'TM'), (190, 'TV'), (191, 'UG'), (192, 'UA'), (193, 'AE'), (194, 'GB'), (195, 'US'), (196, 'UY'), (197, 'UZ'), (198, 'VU'), (199, 'VE'), (200, 'VN'), (201, 'YE'), (202, 'ZM'), (203, 'ZW')], null=True)),
                ('region', models.CharField(max_length=32, null=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('city', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'main_app_location',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$')])),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('bio', models.CharField(max_length=255)),
                ('gender', models.SmallIntegerField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'NON_BINARY'), (3, 'PREFER_NOT_TO_SAY')], null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('frequency_of_physical_activity', models.SmallIntegerField(choices=[(0, 'DAILY'), (1, 'FEW_TIMES_A_WEEK'), (2, 'ONCE_A_WEEK'), (3, 'OCCASIONALLY'), (4, 'RARELY')], null=True)),
                ('social_interaction_importance', models.SmallIntegerField(choices=[(0, 'VERY_IMPORTANT'), (1, 'SOMEWHAT_IMPORTANT'), (2, 'NEUTRAL'), (3, 'NOT_VERY_IMPORTANT'), (4, 'NOT_IMPORTANT_AT_ALL')], null=True)),
                ('preferred_party_size', models.SmallIntegerField(choices=[(0, 'ALONE'), (1, 'SMALL_GROUP'), (2, 'LARGE_GROUP')], null=True)),
                ('formed_relationship_types', models.JSONField(null=True)),
                ('physical_activity_satisfaction', models.SmallIntegerField(choices=[(0, 'VERY_SATISFIED'), (1, 'SATISFIED'), (2, 'NEUTRAL'), (3, 'DISSATISFIED'), (4, 'VERY_DISSATISFIED')], null=True)),
                ('preferred_partner_characteristics', models.JSONField(null=True)),
                ('matched_participation_likelihood', models.SmallIntegerField(choices=[(0, 'VERY_LIKELY'), (1, 'LIKELY'), (2, 'NEUTRAL'), (3, 'UNLIKELY'), (4, 'VERY_UNLIKELY')], null=True)),
                ('preferred_time_of_the_day', models.JSONField(null=True)),
                ('preferred_event_duration', models.SmallIntegerField(null=True)),
                ('gender_preference', models.JSONField(null=True)),
                ('max_travel_distance', models.SmallIntegerField(null=True)),
                ('main_interest', models.SmallIntegerField(choices=[(0, 'SOCIALIZE'), (1, 'FUN'), (2, 'SPORT')], null=True)),
                ('is_capeable', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('xp', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'main_app_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'chat', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=64)),
                ('last_open', models.DateTimeField(null=True)),
                ('notifications', models.SmallIntegerField(choices=[(0, 'NONE'), (1, 'ALL'), (2, 'MENTIONS_ONLY')], default=shared.enums.ChatNotifications['ALL'])),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_chatmember',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(max_length=512)),
                ('time_sent', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attachment', models.CharField(null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_chatmessage',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=131072, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('requirements', models.JSONField(null=True)),
                ('skill_level', models.SmallIntegerField(choices=[(0, 'BEGINNER'), (1, 'INTERMEDIATE'), (2, 'ADVANCED'), (3, 'EXPERT')])),
                ('max_participants', models.IntegerField(null=True)),
                ('allow_spectators', models.BooleanField(default=False)),
                ('min_age', models.SmallIntegerField(null=True)),
                ('max_age', models.SmallIntegerField(null=True)),
                ('accepted_genders', models.JSONField(null=True)),
                ('finished', models.BooleanField(db_index=True, default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.activity')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.chat')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.location')),
            ],
            options={
                'db_table': 'main_app_event',
            },
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'event', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role', models.SmallIntegerField(choices=[(0, 'SPECTATOR'), (1, 'PARTICIPANT'), (2, 'MODERATOR'), (3, 'ORGANIZER')], db_index=True)),
                ('has_participated', models.BooleanField(null=True)),
                ('score', models.SmallIntegerField(choices=[(0, 'VERY_BAD'), (1, 'BAD'), (2, 'NEUTRAL'), (3, 'GOOD'), (4, 'GREAT')], null=True)),
                ('comment', models.CharField(max_length=512, null=True)),
                ('participates', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_eventmember',
            },
        ),
        migrations.CreateModel(
            name='EventMemberLike',
            fields=[
                ('pk', models.CompositePrimaryKey('event', 'user_1', 'user_2', blank=True, editable=False, primary_key=True, serialize=False)),
                ('like', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_eventmemberlike',
            },
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512, null=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='main.event')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_eventreport',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField()),
                ('time_posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.event')),
            ],
            options={
                'db_table': 'main_app_post',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('is_reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.postcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_postcomment',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_post_liked_by',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(through='main.PostLike', through_fields=('post', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PreferredActivity',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'activity', blank=True, editable=False, primary_key=True, serialize=False)),
                ('skill_level', models.SmallIntegerField(choices=[(0, 'BEGINNER'), (1, 'INTERMEDIATE'), (2, 'ADVANCED'), (3, 'EXPERT')])),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_preferredactivity',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('pk', models.CompositePrimaryKey('user_1', 'user_2', blank=True, editable=False, primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'NONE'), (1, 'PENDING'), (2, 'FRIENDS'), (3, 'BLOCKED_BY_ONE'), (5, 'BLOCKED_BY_BOTH'), (6, 'REQUEST_SENT'), (7, 'REQUEST_RECEIVED')], db_index=True)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chat')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_added', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_added_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_relationship',
            },
        ),
        migrations.CreateModel(
            name='UserOtherOption',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'option', blank=True, editable=False, primary_key=True, serialize=False)),
                ('option', models.SmallIntegerField(choices=[(0, 'PREFERRED_PARTNER_CHARACTERISTICS'), (1, 'ACTIVITY'), (2, 'FORMED_RELATIONSHIPS_TYPE')])),
                ('text', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_userotheroption',
            },
        ),
        migrations.CreateModel(
            name='UserPersonalityTrait',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'trait', blank=True, editable=False, primary_key=True, serialize=False)),
                ('trait', models.SmallIntegerField(choices=[(0, 'INTROVERSION')])),
                ('factor', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_userpersonalitytrait',
            },
        ),
        migrations.CreateModel(
            name='UserPrivacySetting',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'setting', blank=True, editable=False, primary_key=True, serialize=False)),
                ('setting', models.SmallIntegerField(choices=[(0, 'LOCATION'), (1, 'AGE'), (2, 'FRIENDS'), (3, 'EMAIL'), (4, 'GENDER')])),
                ('scope', models.SmallIntegerField(choices=[(0, 'NOONE'), (1, 'FRIENDS'), (2, 'EVERYONE')], default=shared.enums.PrivacyScope['EVERYONE'])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_userprivacysetting',
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512, null=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_userreport',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'FRIEND_REQUEST'), (1, 'FRIEND_ACCEPTED'), (2, 'EVENT_FINISHED')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_notification',
                'indexes': [models.Index(fields=['user', 'time_added'], name='main_app_no_user_id_3010a1_idx'), models.Index(fields=['user', 'type'], name='main_app_no_user_id_489ebf_idx')],
            },
        ),
    ]
