# Generated by Django 5.2 on 2026-03-13 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_author(apps, schema_editor):
    Post = apps.get_model("main", "Post")
    EventMember = apps.get_model("main", "EventMember")

    # Delete orphan posts with no event (can't determine author)
    Post.objects.filter(event__isnull=True).delete()

    # Set author to the event's organizer (role=3)
    for post in Post.objects.select_related("event").iterator():
        organizer = (
            EventMember.objects.filter(event_id=post.event_id, role=3)
            .values_list("user_id", flat=True)
            .first()
        )
        if organizer:
            post.author_id = organizer
            post.save(update_fields=["author_id"])
        else:
            # No organizer found — delete the post
            post.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        # Step 1: Add author as nullable
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Step 2: Backfill author from event organizer
        migrations.RunPython(backfill_author, migrations.RunPython.noop),
        # Step 3: Make author non-nullable
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Step 4: Change event FK to SET_NULL
        migrations.AlterField(
            model_name="post",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="main.event",
            ),
        ),
    ]
