# Generated by Django 5.2 on 2026-03-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_decouple_posts_from_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.event'),
        ),
    ]
