# Generated by Django 5.2 on 2026-03-14 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_post_comments(apps, schema_editor):
    PostComment = apps.get_model("main", "PostComment")
    Comment = apps.get_model("main", "Comment")

    old_to_new = {}

    # First pass: copy top-level comments (no parent)
    for pc in PostComment.objects.filter(is_reply_to__isnull=True).order_by("id"):
        new = Comment.objects.create(
            user_id=pc.user_id,
            post_id=pc.post_id,
            text=pc.text,
        )
        # Preserve original timestamp
        Comment.objects.filter(pk=new.pk).update(time_posted=pc.time_posted)
        old_to_new[pc.id] = new.id

    # Second pass: copy replies
    for pc in PostComment.objects.filter(is_reply_to__isnull=False).order_by("id"):
        parent_new_id = old_to_new.get(pc.is_reply_to_id)
        new = Comment.objects.create(
            user_id=pc.user_id,
            post_id=pc.post_id,
            text=pc.text,
            parent_id=parent_new_id,
        )
        Comment.objects.filter(pk=new.pk).update(time_posted=pc.time_posted)
        old_to_new[pc.id] = new.id


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_comments', to='main.event')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_comment',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_comment_liked_by',
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.RunPython(migrate_post_comments, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
