# Generated by Django 5.2 on 2026-03-14 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import shared.enums


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_title_comment_commentlike_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='commentlike',
                    name='id',
                ),
                migrations.RemoveField(
                    model_name='postlike',
                    name='id',
                ),
                migrations.AddField(
                    model_name='commentlike',
                    name='pk',
                    field=models.CompositePrimaryKey('comment', 'user', blank=True, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AddField(
                    model_name='postlike',
                    name='pk',
                    field=models.CompositePrimaryKey('post', 'user', blank=True, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterUniqueTogether(
                    name='commentlike',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'NEW_FOLLOWER'), (2, 'EVENT_FINISHED')]),
        ),
        migrations.AlterField(
            model_name='userprivacysetting',
            name='scope',
            field=models.SmallIntegerField(choices=[(0, 'NOONE'), (1, 'FOLLOWERS'), (2, 'EVERYONE')], default=shared.enums.PrivacyScope['EVERYONE']),
        ),
        migrations.AlterField(
            model_name='userprivacysetting',
            name='setting',
            field=models.SmallIntegerField(choices=[(0, 'LOCATION'), (1, 'AGE'), (2, 'FOLLOWERS'), (3, 'EMAIL'), (4, 'GENDER')]),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('pk', models.CompositePrimaryKey('blocker', 'blocked', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_set', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_block',
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DirectChat',
                    fields=[
                        ('pk', models.CompositePrimaryKey('user_1', 'user_2', blank=True, editable=False, primary_key=True, serialize=False)),
                        ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direct_chat', to='main.chat')),
                        ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_chats_as_user_1', to=settings.AUTH_USER_MODEL)),
                        ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_chats_as_user_2', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'main_app_directchat',
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('pk', models.CompositePrimaryKey('follower', 'following', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_follow',
            },
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
