# Generated by Django 5.2 on 2026-03-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_event_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chat',
        ),
    ]
