# Generated by Django 5.2 on 2026-03-15 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_event_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='main.chat')),
            ],
            options={
                'db_table': 'main_app_groupchat',
            },
        ),
    ]
