# Generated by Django 5.2 on 2026-03-15 18:56

from django.db import migrations


def backfill_groupchat(apps, schema_editor):
    Chat = apps.get_model("main", "Chat")
    DirectChat = apps.get_model("main", "DirectChat")
    GroupChat = apps.get_model("main", "GroupChat")

    direct_chat_ids = set(
        DirectChat.objects.values_list("chat_id", flat=True)
    )
    group_chats_to_create = [
        GroupChat(chat_id=chat_id, name="")
        for chat_id in Chat.objects.values_list("id", flat=True)
        if chat_id not in direct_chat_ids
    ]
    GroupChat.objects.bulk_create(group_chats_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_groupchat"),
    ]

    operations = [
        migrations.RunPython(backfill_groupchat, migrations.RunPython.noop),
    ]
