# Generated by Django 5.2 on 2026-03-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_backfill_groupchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotheroption',
            name='option',
            field=models.SmallIntegerField(choices=[(0, 'PREFERRED_PARTNER_CHARACTERISTICS'), (1, 'ACTIVITY'), (2, 'FORMED_RELATIONSHIPS_KIND')]),
        ),
    ]
