# Generated by Django 5.2 on 2026-03-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_userotheroption_option'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='main_app_no_user_id_489ebf_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='kind',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'kind'], name='main_app_no_user_id_aa05cf_idx'),
        ),
    ]
