# Generated by Django 5.2 on 2026-03-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_notification_type_to_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='formed_relationship_types',
            new_name='formed_relationship_kinds',
        ),
    ]
