# Generated by Django 5.2 on 2026-05-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_formed_relationship_types_user_formed_relationship_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
