# Generated by Django 5.2 on 2026-05-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_event_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.SmallIntegerField(choices=[(0, 'NEW_FOLLOWER'), (2, 'EVENT_FINISHED'), (3, 'EVENT_STARTED'), (4, 'EVENT_CANCELLED')]),
        ),
    ]
