# Generated by Django 5.2 on 2026-05-21 11:38

from django.db import migrations, models

import shared.enums


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivacysetting',
            name='scope',
            field=models.SmallIntegerField(choices=[(0, 'NOONE'), (1, 'FOLLOWERS'), (2, 'EVERYONE'), (3, 'MUTUALS')], default=shared.enums.PrivacyScope['NOONE']),
        ),
        migrations.AlterField(
            model_name='userprivacysetting',
            name='setting',
            field=models.SmallIntegerField(choices=[(0, 'LOCATION'), (1, 'AGE'), (2, 'FOLLOWERS'), (3, 'EMAIL'), (4, 'GENDER'), (5, 'POSTS')]),
        ),
    ]
