# Generated by Django 5.2 on 2026-05-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_email_privacy_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='has_participated',
            field=models.BooleanField(default=True),
        ),
    ]
