# Generated by Django 5.2 on 2026-05-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_lowercase_usernames_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=512),
        ),
    ]
