# Generated by Django 5.2 on 2026-05-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='nickname',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
