# Generated by Django 5.2 on 2026-05-26 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import shared.enums


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_null_chatmember_nicknames'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='kind',
            field=models.SmallIntegerField(choices=[(0, 'TEXT'), (1, 'MEMBER_ADDED'), (2, 'MEMBER_REMOVED'), (3, 'NICKNAME_CHANGED')], default=shared.enums.ChatMessageKind['TEXT']),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text_content',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
