# Generated by Django 5.2 on 2026-05-26 15:17

import shared.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_chatmessage_kind_chatmessage_target_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='kind',
            field=models.SmallIntegerField(choices=[(0, 'TEXT'), (1, 'NICKNAME_CHANGED'), (2, 'MEMBER_ADDED'), (3, 'MEMBER_REMOVED')], default=shared.enums.ChatMessageKind['TEXT']),
        ),
    ]
