# Generated by Django 5.2 on 2026-05-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_chatmessage_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
