# Generated by Django 5.2 on 2026-06-02 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_chatmember_left_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='formed_relationship_kinds',
        ),
        migrations.RemoveField(
            model_name='user',
            name='frequency_of_physical_activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender_preference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='main_interest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matched_participation_likelihood',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_travel_distance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='physical_activity_satisfaction',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_event_duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_partner_characteristics',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_party_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_time_of_the_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_interaction_importance',
        ),
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'day_of_week', 'time_of_day', blank=True, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'MONDAY'), (1, 'TUESDAY'), (2, 'WEDNESDAY'), (3, 'THURSDAY'), (4, 'FRIDAY'), (5, 'SATURDAY'), (6, 'SUNDAY')])),
                ('time_of_day', models.SmallIntegerField(choices=[(0, 'MORNING'), (1, 'AFTERNOON'), (2, 'EVENING'), (3, 'NIGHT')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_useravailability',
            },
        ),
        migrations.CreateModel(
            name='UserParticipationGroup',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'group_kind', blank=True, editable=False, primary_key=True, serialize=False)),
                ('group_kind', models.SmallIntegerField(choices=[(0, 'FIRST_HAND'), (1, 'SECOND_HAND'), (2, 'COMMON_INTERESTS'), (3, 'ROMANTIC_ONE_ON_ONE'), (4, 'ROMANTIC_GROUP')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_userparticipationgroup',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_session_duration', models.SmallIntegerField(null=True)),
                ('organizing_openness', models.SmallIntegerField(choices=[(0, 'NO'), (1, 'SOMETIMES'), (2, 'YES')], null=True)),
                ('leadership_inclination', models.SmallIntegerField(null=True)),
                ('max_travel_distance', models.SmallIntegerField(null=True)),
                ('weekly_activity_target', models.SmallIntegerField(null=True)),
                ('preferred_difficulty', models.SmallIntegerField(choices=[(0, 'BEGINNER'), (1, 'INTERMEDIATE'), (2, 'ADVANCED'), (3, 'EXPERT')], null=True)),
                ('pushes_through_discomfort', models.SmallIntegerField(null=True)),
                ('preferred_group_size', models.SmallIntegerField(null=True)),
                ('acquaintance_preference', models.SmallIntegerField(choices=[(0, 'NOBODY'), (1, 'ONE'), (2, 'TWO'), (3, 'THREE_PLUS'), (4, 'EVERYONE')], null=True)),
                ('mixed_gender_comfort', models.SmallIntegerField(null=True)),
                ('enjoys_meeting_new_people', models.SmallIntegerField(null=True)),
                ('activity_vs_social', models.SmallIntegerField(null=True)),
                ('motivated_by_competition', models.SmallIntegerField(null=True)),
                ('planning_horizon', models.SmallIntegerField(null=True)),
                ('feels_like_burden', models.SmallIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_app_userpreferences',
            },
        ),
    ]
