# Generated by Django 5.2 on 2026-06-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_user_formed_relationship_kinds_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreferredActivity',
            new_name='UserPreferredActivity',
        ),
    ]
