# Generated by Django 5.2 on 2026-06-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_preferredactivity_userpreferredactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='mixed_gender_comfort',
        ),
    ]
