# Generated by Django 5.2 on 2026-06-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_userpreferences_mixed_gender_comfort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferred_difficulty',
        ),
    ]
