# Generated by Django 5.2 on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


def populate_preferences(apps, schema_editor):
    """Copy each row's owning user onto the new preferences FK.

    User <-> UserPreferences is 1:1 (OneToOneField), so the preferences row is
    created lazily for any user that answered these survey questions without
    having a preferences row yet.
    """
    UserPreferences = apps.get_model("main", "UserPreferences")
    for model_name in (
        "UserAvailability",
        "UserParticipationGroup",
        "UserPreferredActivity",
    ):
        Model = apps.get_model("main", model_name)
        prefs_by_user = {}
        for row in Model.objects.all():
            user_id = row.user_id
            pref_id = prefs_by_user.get(user_id)
            if pref_id is None:
                pref, _ = UserPreferences.objects.get_or_create(user_id=user_id)
                pref_id = pref.pk
                prefs_by_user[user_id] = pref_id
            row.preferences_id = pref_id
            row.save(update_fields=["preferences"])


def reverse_populate(apps, schema_editor):
    """Copy the preferences' owning user back onto the user FK."""
    for model_name in (
        "UserAvailability",
        "UserParticipationGroup",
        "UserPreferredActivity",
    ):
        Model = apps.get_model("main", model_name)
        for row in Model.objects.select_related("preferences").all():
            row.user_id = row.preferences.user_id
            row.save(update_fields=["user"])


def swap_primary_key(table, columns):
    """Drop the existing composite PK and recreate it on ``columns``.

    Django 5.2 emits no DDL when a ``CompositePrimaryKey``'s component fields
    change, so the actual PostgreSQL ``PRIMARY KEY`` constraint must be swapped
    by hand. The current PK name is looked up dynamically so we don't depend on
    PostgreSQL's auto-generated constraint name.
    """
    cols = ", ".join(columns)
    return f"""
        DO $$
        DECLARE pk_name text;
        BEGIN
            SELECT conname INTO pk_name
              FROM pg_constraint
             WHERE conrelid = '{table}'::regclass AND contype = 'p';
            IF pk_name IS NOT NULL THEN
                EXECUTE 'ALTER TABLE {table} DROP CONSTRAINT ' || quote_ident(pk_name);
            END IF;
        END $$;
        ALTER TABLE {table} ADD PRIMARY KEY ({cols});
    """


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_remove_userpreferences_preferred_difficulty"),
    ]

    operations = [
        # 1. Add the new FK as nullable so existing rows can be backfilled.
        migrations.AddField(
            model_name="useravailability",
            name="preferences",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="main.userpreferences",
            ),
        ),
        migrations.AddField(
            model_name="userparticipationgroup",
            name="preferences",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participation_groups",
                to="main.userpreferences",
            ),
        ),
        migrations.AddField(
            model_name="userpreferredactivity",
            name="preferences",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferred_activities",
                to="main.userpreferences",
            ),
        ),
        # 2. Backfill preferences from the owning user (still the PK at this point).
        migrations.RunPython(populate_preferences, reverse_populate),
        # 3. Make the new FK non-nullable now that every row is populated.
        migrations.AlterField(
            model_name="useravailability",
            name="preferences",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="main.userpreferences",
            ),
        ),
        migrations.AlterField(
            model_name="userparticipationgroup",
            name="preferences",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participation_groups",
                to="main.userpreferences",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferredactivity",
            name="preferences",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferred_activities",
                to="main.userpreferences",
            ),
        ),
        # 4. Swap the real PostgreSQL primary key constraint onto the new FK.
        #    (Django emits no DDL for the CompositePrimaryKey change below, so we
        #    do it explicitly here while user_id still exists.)
        migrations.RunSQL(
            swap_primary_key(
                "main_app_useravailability",
                ["preferences_id", "day_of_week", "time_of_day"],
            ),
            swap_primary_key(
                "main_app_useravailability",
                ["user_id", "day_of_week", "time_of_day"],
            ),
        ),
        migrations.RunSQL(
            swap_primary_key(
                "main_app_userparticipationgroup",
                ["preferences_id", "group_kind"],
            ),
            swap_primary_key(
                "main_app_userparticipationgroup",
                ["user_id", "group_kind"],
            ),
        ),
        migrations.RunSQL(
            swap_primary_key(
                "main_app_preferredactivity",
                ["preferences_id", "activity_id"],
            ),
            swap_primary_key(
                "main_app_preferredactivity",
                ["user_id", "activity_id"],
            ),
        ),
        # 5. Update Django's model state to the new composite PK (no DDL emitted).
        migrations.AlterField(
            model_name="useravailability",
            name="pk",
            field=models.CompositePrimaryKey(
                "preferences",
                "day_of_week",
                "time_of_day",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userparticipationgroup",
            name="pk",
            field=models.CompositePrimaryKey(
                "preferences",
                "group_kind",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userpreferredactivity",
            name="pk",
            field=models.CompositePrimaryKey(
                "preferences",
                "activity",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        # 6. Drop the now-unused user FK (its old PK was already replaced above).
        migrations.RemoveField(
            model_name="useravailability",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userparticipationgroup",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userpreferredactivity",
            name="user",
        ),
    ]
