# Generated by Django 5.2rc1 on 2025-03-20 20:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('trait', models.SmallIntegerField(choices=[(0, 'INTROVERSION')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdressLocation',
            fields=[
                ('baselocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.baselocation')),
                ('address_line_1', models.CharField(max_length=64)),
                ('address_line_2', models.CharField(max_length=64)),
                ('post_code', models.IntegerField()),
                ('country_code', models.CharField(max_length=2)),
                ('region', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main_app.baselocation',),
        ),
        migrations.CreateModel(
            name='MoveusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('bio', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('frequency_of_physical_activity', models.SmallIntegerField(choices=[(0, 'DAILY'), (1, 'FEW_TIMES_A_WEEK'), (2, 'ONCE_A_WEEK'), (3, 'OCCASIONALLY'), (4, 'RARELY')])),
                ('social_iteraction_importance', models.SmallIntegerField(choices=[(0, 'VERY_IMPORTANT'), (1, 'SOMEWHAT_IMPORTANT'), (2, 'NEUTRAL'), (3, 'NOT_VERY_IMPORTANT'), (4, 'NOT_IMPORTANT_AT_ALL')])),
                ('preferred_party_size', models.SmallIntegerField(choices=[(0, 'ALONE'), (1, 'SMALL_GROUP'), (2, 'LARGE_GROUP')])),
                ('new_friendships_formed', models.BooleanField()),
                ('formed_relationships_type', models.JSONField()),
                ('physical_activity_satisfaction', models.SmallIntegerField(choices=[(0, 'VERY_SATISFIED'), (1, 'SATISFIED'), (2, 'NEUTRAL'), (3, 'DISSATISFIED'), (4, 'VERY_DISSATISFIED')])),
                ('preferred_partned_characteristics', models.JSONField()),
                ('matched_participation_likelihood', models.SmallIntegerField(choices=[(0, 'VERY_LIKELY'), (1, 'LIKELY'), (2, 'NEUTRAL'), (3, 'UNLIKELY'), (4, 'VERY_UNLIKELY')])),
                ('is_capeable', models.BooleanField()),
                ('agreed_to_toc', models.BooleanField()),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('xp', models.IntegerField(default=0)),
                ('last_online', models.DateTimeField()),
                ('passed_tutorial', models.BooleanField()),
                ('img_url', models.URLField()),
                ('verified', models.BooleanField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.baselocation')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonalityTrait',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'trait', blank=True, editable=False, primary_key=True, serialize=False)),
                ('factor', models.FloatField()),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.personalitytrait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteLocation',
            fields=[
                ('adresslocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.adresslocation')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main_app.adresslocation',),
        ),
    ]
