# Generated by Django 5.2rc1 on 2025-03-20 21:46

import django.db.models.deletion
import main_app.models.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('time_created', models.DateTimeField()),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherOption',
            fields=[
                ('option', models.SmallIntegerField(choices=[(0, 'PREFERRED_PARTNER_CHARACTHERISTICS'), (1, 'ACTIVITY'), (2, 'FORMED_RELATIONSHIPS_TYPE')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySetting',
            fields=[
                ('setting', models.SmallIntegerField(choices=[(0, 'LOCATION'), (1, 'AGE'), (2, 'FRIENDS'), (3, 'NAME'), (4, 'EMAIL')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'chat', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=64)),
                ('last_open', models.DateTimeField()),
                ('notifications', models.SmallIntegerField(choices=[(0, 'NONE'), (1, 'ALL'), (2, 'MENTIONS_ONLY')], default=main_app.models.enums.ChatNotifications['ALL'])),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField()),
                ('time_sent', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('min_age', models.SmallIntegerField()),
                ('max_age', models.SmallIntegerField()),
                ('img_url', models.URLField()),
                ('requirements', models.CharField(max_length=512)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.chat')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.baselocation')),
            ],
        ),
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('pk', models.CompositePrimaryKey('event', 'activity', blank=True, editable=False, primary_key=True, serialize=False)),
                ('skill_level', models.SmallIntegerField(choices=[(0, 'BEGINNER'), (1, 'INTERMEDIATE'), (2, 'ADVANCED'), (3, 'EXPERT')])),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.activity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'event', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role', models.SmallIntegerField(choices=[(0, 'PARTICIPANT'), (1, 'ORGANIZER'), (2, 'MODERATOR'), (3, 'SPECTATOR')])),
                ('score', models.SmallIntegerField(choices=[(0, 'VERY_BAD'), (1, 'BAD'), (2, 'NEUTRAL'), (3, 'GOOD'), (4, 'GREAT')])),
                ('comment', models.CharField(max_length=512)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='main_app.event')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField()),
                ('time_posted', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.event')),
                ('liked_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chatmessage')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('is_reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.postcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferredActivity',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'activity', blank=True, editable=False, primary_key=True, serialize=False)),
                ('skill_level', models.SmallIntegerField(choices=[(0, 'BEGINNER'), (1, 'INTERMEDIATE'), (2, 'ADVANCED'), (3, 'EXPERT')])),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('status', models.SmallIntegerField(choices=[(0, 'NONE'), (1, 'PENDING'), (2, 'FRIENDS'), (3, 'BLOCKED_BY_FIRST'), (4, 'BLOCKED_BY_SECOND'), (5, 'BLOCKED_BY_BOTH')])),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chat')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_added', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOtherOption',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'option', blank=True, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=128)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.otheroption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivacySetting',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'setting', blank=True, editable=False, primary_key=True, serialize=False)),
                ('scope', models.SmallIntegerField(choices=[(0, 'NOONE'), (1, 'FRIENDS'), (2, 'SAME_EVENT'), (3, 'EVERYONE')], default=main_app.models.enums.PrivacyScope['EVERYONE'])),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.privacysetting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
