# Generated by Django 5.2rc1 on 2025-03-20 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_chat_otheroption_privacysetting_activity_chatmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveususer',
            name='agreed_to_toc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='formed_relationships_type',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='frequency_of_physical_activity',
            field=models.SmallIntegerField(choices=[(0, 'DAILY'), (1, 'FEW_TIMES_A_WEEK'), (2, 'ONCE_A_WEEK'), (3, 'OCCASIONALLY'), (4, 'RARELY')], null=True),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='is_capeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='last_online',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.baselocation'),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='matched_participation_likelihood',
            field=models.SmallIntegerField(choices=[(0, 'VERY_LIKELY'), (1, 'LIKELY'), (2, 'NEUTRAL'), (3, 'UNLIKELY'), (4, 'VERY_UNLIKELY')], null=True),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='passed_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='physical_activity_satisfaction',
            field=models.SmallIntegerField(choices=[(0, 'VERY_SATISFIED'), (1, 'SATISFIED'), (2, 'NEUTRAL'), (3, 'DISSATISFIED'), (4, 'VERY_DISSATISFIED')], null=True),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='preferred_partned_characteristics',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='preferred_party_size',
            field=models.SmallIntegerField(choices=[(0, 'ALONE'), (1, 'SMALL_GROUP'), (2, 'LARGE_GROUP')], null=True),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='social_iteraction_importance',
            field=models.SmallIntegerField(choices=[(0, 'VERY_IMPORTANT'), (1, 'SOMEWHAT_IMPORTANT'), (2, 'NEUTRAL'), (3, 'NOT_VERY_IMPORTANT'), (4, 'NOT_IMPORTANT_AT_ALL')], null=True),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
