# Generated by Django 5.2rc1 on 2025-03-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_moveususer_agreed_to_toc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='new_friendships_formed',
            field=models.BooleanField(null=True),
        ),
    ]
