# Generated by Django 5.2rc1 on 2025-03-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_moveususer_new_friendships_formed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='event',
            name='min_age',
        ),
        migrations.AddField(
            model_name='User',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'NON_BINARY'), (3, 'PREFFER_NOT_TO_SAY')], default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='requirements',
            field=models.JSONField(),
        ),
    ]
