# Generated by Django 5.2rc1 on 2025-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_event_max_age_remove_event_min_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotheroption',
            name='option',
            field=models.SmallIntegerField(choices=[(0, 'PREFERRED_PARTNER_CHARACTHERISTICS'), (1, 'ACTIVITY'), (2, 'FORMED_RELATIONSHIPS_TYPE')]),
        ),
        migrations.AlterField(
            model_name='userpersonalitytrait',
            name='trait',
            field=models.SmallIntegerField(choices=[(0, 'INTROVERSION')]),
        ),
        migrations.AlterField(
            model_name='userprivacysetting',
            name='setting',
            field=models.SmallIntegerField(choices=[(0, 'LOCATION'), (1, 'AGE'), (2, 'FRIENDS'), (3, 'NAME'), (4, 'EMAIL')]),
        ),
        migrations.DeleteModel(
            name='OtherOption',
        ),
        migrations.DeleteModel(
            name='PersonalityTrait',
        ),
        migrations.DeleteModel(
            name='PrivacySetting',
        ),
    ]
