# Generated by Django 5.2rc1 on 2025-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_userotheroption_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'NON_BINARY'), (3, 'PREFFER_NOT_TO_SAY')], null=True),
        ),
    ]
