# Generated by Django 5.2rc1 on 2025-03-26 20:13

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_moveususer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.event'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='userprivacysetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
