# Generated by Django 5.2rc1 on 2025-03-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_post_event_alter_post_time_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='time_posted',
            field=models.DateTimeField(null=True),
        ),
    ]
