# Generated by Django 5.2rc1 on 2025-03-26 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_postcomment_time_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='is_reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='main_app.postcomment'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
