# Generated by Django 5.2rc1 on 2025-03-26 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_post_time_posted_alter_postcomment_is_reply_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='is_reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='main_app.postcomment'),
        ),
    ]
