# Generated by Django 5.2rc1 on 2025-03-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_chat_name_alter_chat_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='last_open',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='nickname',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
