# Generated by Django 5.2rc1 on 2025-03-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_chatmember_last_open_alter_chatmember_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='nickname',
            field=models.CharField(max_length=64),
        ),
    ]
