# Generated by Django 5.2rc1 on 2025-03-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_chatmember_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
