# Generated by Django 5.2rc1 on 2025-03-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_relationship_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.chat'),
        ),
    ]
