# Generated by Django 5.2rc1 on 2025-03-31 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_relationship_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.chat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='img_url',
            field=models.URLField(default='default.png'),
        ),
        migrations.AlterField(
            model_name='event',
            name='requirements',
            field=models.JSONField(null=True),
        ),
    ]
