# Generated by Django 5.2rc1 on 2025-04-01 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_event_chat_alter_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('address_line_1', models.CharField(max_length=64)),
                ('address_line_2', models.CharField(max_length=64)),
                ('zip_code', models.CharField()),
                ('country_code', models.CharField(max_length=2)),
                ('region', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='institutelocation',
            name='adresslocation_ptr',
        ),
        migrations.RemoveField(
            model_name='baselocation',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.location'),
        ),
        migrations.AlterField(
            model_name='moveususer',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.location'),
        ),
        migrations.DeleteModel(
            name='AdressLocation',
        ),
        migrations.DeleteModel(
            name='InstituteLocation',
        ),
        migrations.DeleteModel(
            name='BaseLocation',
        ),
    ]
