# Generated by Django 5.2rc1 on 2025-04-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_location_remove_institutelocation_adresslocation_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveususer',
            name='agreed_to_toc',
        ),
    ]
