# Generated by Django 5.2rc1 on 2025-04-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_moveususer_agreed_to_toc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='User',
            name='last_online',
        ),
    ]
