# Generated by Django 5.2rc1 on 2025-04-01 22:57

import main_app.models.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_remove_moveususer_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address_line_1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line_2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprivacysetting',
            name='scope',
            field=models.SmallIntegerField(choices=[(0, 'NOONE'), (1, 'FRIENDS'), (2, 'EVERYONE')], default=main_app.models.enums.PrivacyScope['EVERYONE']),
        ),
        migrations.AlterField(
            model_name='userprivacysetting',
            name='setting',
            field=models.SmallIntegerField(choices=[(0, 'LOCATION'), (1, 'AGE'), (2, 'FRIENDS'), (3, 'EMAIL')]),
        ),
    ]
