# Generated by Django 5.2rc1 on 2025-04-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_location_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='has_ballz',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.SmallIntegerField(choices=[(0, 'HIKING'), (1, 'RUNNING'), (2, 'SOCCER'), (3, 'TENNIS'), (4, 'GYM'), (5, 'SEX')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='User',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'NON_BINARY'), (3, 'PREFER_NOT_TO_SAY')], null=True),
        ),
        migrations.AlterField(
            model_name='userotheroption',
            name='option',
            field=models.SmallIntegerField(choices=[(0, 'PREFERRED_PARTNER_CHARACTERISTICS'), (1, 'ACTIVITY'), (2, 'FORMED_RELATIONSHIPS_TYPE')]),
        ),
        migrations.AlterField(
            model_name='userprivacysetting',
            name='setting',
            field=models.SmallIntegerField(choices=[(0, 'LOCATION'), (1, 'AGE'), (2, 'FRIENDS'), (3, 'EMAIL'), (4, 'GENDER')]),
        ),
    ]
