# Generated by Django 5.2rc1 on 2025-04-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_activity_name_activity_has_ballz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='img_url',
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.SmallIntegerField(choices=[(0, 'HIKING'), (1, 'RUNNING'), (2, 'SOCCER'), (3, 'TENNIS'), (4, 'GYM'), (5, 'MAKING_LOVE')], primary_key=True, serialize=False),
        ),
    ]
