# Generated by Django 5.2 on 2025-04-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_remove_event_img_url_alter_activity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='User',
            old_name='preferred_partned_characteristics',
            new_name='preferred_partner_characteristics',
        ),
    ]
