# Generated by Django 5.2 on 2025-04-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_rename_preferred_partned_characteristics_moveususer_preferred_partner_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='id',
        ),
        migrations.AddField(
            model_name='eventmember',
            name='has_participated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='pk',
            field=models.CompositePrimaryKey('user_1', 'user_2', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='comment',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main_app.event'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='score',
            field=models.SmallIntegerField(choices=[(0, 'VERY_BAD'), (1, 'BAD'), (2, 'NEUTRAL'), (3, 'GOOD'), (4, 'GREAT')], null=True),
        ),
    ]
