# Generated by Django 5.2 on 2025-04-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_remove_relationship_id_eventmember_has_participated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='social_iteraction_importance',
            new_name='social_interaction_importance',
        ),
    ]
