# Generated by Django 5.2 on 2025-04-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_rename_social_iteraction_importance_user_social_interaction_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new_friendships_formed',
        ),
    ]
