# Generated by Django 5.2 on 2025-04-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_remove_user_new_friendships_formed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='formed_relationships_type',
            new_name='formed_relationship_types',
        ),
    ]
