# Generated by Django 5.2 on 2025-04-07 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_rename_formed_relationships_type_user_formed_relationship_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='skill_level',
            field=models.SmallIntegerField(choices=[(0, 'BEGINNER'), (1, 'INTERMEDIATE'), (2, 'ADVANCED'), (3, 'EXPERT')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preferredactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EventActivity',
        ),
    ]
