# Generated by Django 5.2 on 2025-04-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_location_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
