# Generated by Django 5.2 on 2025-04-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_remove_user_location_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'NONE'), (1, 'PENDING'), (2, 'FRIENDS'), (3, 'BLOCKED_BY_FIRST'), (4, 'BLOCKED_BY_SECOND'), (5, 'BLOCKED_BY_BOTH'), (6, 'REQUEST_SENT'), (7, 'REQUEST_RECEIVED')]),
        ),
    ]
