# Generated by Django 5.2 on 2025-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'SPECTATOR'), (1, 'PARTICIPANT'), (2, 'MODERATOR'), (3, 'ORGANIZER')]),
        ),
    ]
