# Generated by Django 5.2 on 2025-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_event_max_participants_alter_eventmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_spectators',
            field=models.BooleanField(default=False),
        ),
    ]
