# Generated by Django 5.2 on 2025-04-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_event_allow_spectators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='has_participated',
            field=models.BooleanField(default=False),
        ),
    ]
