# Generated by Django 5.2 on 2025-04-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_alter_eventmember_has_participated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.SmallIntegerField(choices=[(0, 'HIKING'), (1, 'RUNNING'), (2, 'SOCCER'), (3, 'TENNIS'), (4, 'GYM')], primary_key=True, serialize=False),
        ),
    ]
