# Generated by Django 5.2 on 2025-04-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='has_ballz',
        ),
    ]
