# Generated by Django 5.2 on 2025-04-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_remove_activity_has_ballz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_time_of_the_day',
            field=models.JSONField(null=True),
        ),
    ]
