# Generated by Django 5.2 on 2025-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_user_preferred_time_of_the_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_url',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
