# Generated by Django 5.2 on 2025-04-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_remove_user_img_url_location_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passed_tutorial',
        ),
    ]
