# Generated by Django 5.2 on 2025-04-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_remove_user_passed_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepted_genders',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='min_age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_preference',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='main_interest',
            field=models.SmallIntegerField(choices=[(0, 'SOCIALIZE'), (1, 'FUN'), (2, 'SPORT')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_travel_distance',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_event_duration',
            field=models.SmallIntegerField(null=True),
        ),
    ]
