# Generated by Django 5.2 on 2025-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_event_accepted_genders_event_max_age_event_min_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='has_participated',
            field=models.BooleanField(null=True),
        ),
    ]
