# Generated by Django 5.2 on 2025-04-18 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_alter_eventmember_has_participated'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMemberLike',
            fields=[
                ('pk', models.CompositePrimaryKey('event', 'user_1', 'user_2', blank=True, editable=False, primary_key=True, serialize=False)),
                ('like', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.event')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
