# Generated by Django 5.2 on 2025-04-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_eventmemberlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='participates',
            field=models.BooleanField(default=False),
        ),
    ]
