# Generated by Django 5.2 on 2025-05-08 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_remove_chat_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main_app.chat'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main_app.chat'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
