# Generated by Django 5.2 on 2025-05-09 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_alter_chatmember_chat_alter_chatmessage_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='text_content',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main_app.event'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'FRIEND_REQUEST'), (1, 'FRIEND_ACCEPTED'), (2, 'EVENT_CANCELED'), (3, 'EVENT_FINISHED')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
