# Generated by Django 5.2 on 2025-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0053_alter_chatmessage_text_content_alter_post_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'FRIEND_REQUEST'), (1, 'FRIEND_ACCEPTED'), (2, 'EVENT_FINISHED')]),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
