# Generated by Django 5.2 on 2025-05-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0054_chatmessage_attachment_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreport',
            name='comment',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='comment',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
