# Generated by Django 5.2 on 2025-05-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_alter_eventreport_comment_alter_userreport_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'NONE'), (1, 'PENDING'), (2, 'FRIENDS'), (3, 'BLOCKED_BY_ONE'), (5, 'BLOCKED_BY_BOTH'), (6, 'REQUEST_SENT'), (7, 'REQUEST_RECEIVED')]),
        ),
    ]
