# Generated by Django 5.2 on 2025-05-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_alter_relationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.SmallIntegerField(choices=[(5, 'AEROBICS'), (6, 'BADMINTON'), (7, 'BASEBALL'), (8, 'BASKETBALL'), (9, 'BIKING'), (10, 'BOXING'), (11, 'CLIMBING'), (12, 'CRICKET'), (13, 'CROSSFIT'), (14, 'DANCING'), (15, 'FOOTBALL'), (16, 'GOLF'), (4, 'GYM'), (17, 'HANDBALL'), (0, 'HIKING'), (18, 'KAYAKING'), (19, 'MARTIAL_ARTS'), (20, 'PILATES'), (21, 'RUGBY'), (1, 'RUNNING'), (22, 'SAILING'), (23, 'SKATEBOARDING'), (24, 'SKIING'), (25, 'SNOWBOARDING'), (2, 'SOCCER'), (26, 'SURFING'), (27, 'SWIMMING'), (3, 'TENNIS'), (28, 'VOLLEYBALL'), (29, 'WALKING'), (30, 'YOGA')], primary_key=True, serialize=False),
        ),
    ]
